function [dat] = metac_int_ehgf_binary(dat)


%% plot settings
% dock all figures
set(0,'DefaultFigureWindowStyle','docked')

%% _______________
% sim int HGF (handcrafted). not MAB yet though...
n=1;
dat.ehgfb.sub(n).sim = tapas_simModel(dat.u_bin(:,n),...
    'tapas_ehgf_binary',...
    [NaN 0 1 NaN 1 1 NaN 0 0 1 1 NaN -2 2],...
    'tapas_beta_obs',...
    log(128),...
    12345 ...
    );
tapas_ehgf_binary_plotTraj(dat.ehgfb.sub(n).sim)
hold on;
ax=axis;
fill([dat.trials, fliplr(dat.trials)],...
    [ax(3)*ones(1,length(dat.trials)), ax(4)*ones(1,length(dat.trials))],...
    [dat.u_mab4', fliplr(dat.u_mab4')], 'EdgeAlpha', 0, 'FaceAlpha', 0.15);
colormap(flipud(colormap("autumn")))
hold off;
figdir = fullfile('figures', 'int_ehgf_binary', ['sim_sub' num2str(n)]);
print(figdir, '-dpng');

%% fit int HGF. not MAB yet though...
for n = 1:size(dat.u_bin,2)
    dat.ehgfb.sub(n).est = tapas_fitModel(dat.y_pred(:,n),...
        dat.u_bin(:,n),...
        tapas_ehgf_binary_config,...
        tapas_beta_obs_config,...
        tapas_quasinewton_optim_config ...
        );
    tapas_ehgf_binary_plotTraj(dat.ehgfb.sub(n).est)
    hold on;
    ax=axis;
    fill([dat.trials, fliplr(dat.trials)],...
        [ax(3)*ones(1,length(dat.trials)), ax(4)*ones(1,length(dat.trials))],...
        [dat.u_mab4', fliplr(dat.u_mab4')], 'EdgeAlpha', 0, 'FaceAlpha', 0.15);
    colormap(flipud(colormap("autumn")))
    hold off;
    figdir = fullfile('figures', 'int_ehgf_binary', ['est_sub' num2str(n)]);
    print(figdir, '-dpng');
end


end