function [dat] = metac_raw_PE_mc_ehgf(dat)


%% plot settings
% dock all figures
set(0,'DefaultFigureWindowStyle','docked')

%% ____________
% sim metacognitive HGF + beta obs (handcrafted)
n=1;
dat.ehgf_PE_abs.sub(n).sim = tapas_simModel((1.-abs(dat.u_pe(:,n))),...
    'tapas_ehgf',...
    [0 1 1 1 0 0 1 -2 -2 10],...
    'tapas_beta_obs',...
    log(128),...
    12345 ...
    );
tapas_ehgf_plotTraj(dat.ehgf_PE_abs.sub(n).sim)
figdir = fullfile('figures', 'mc_ehgf', ['sim_sub' num2str(n)]);
print(figdir, '-dpng');


%% fit metacognitive HGF + gaussian obs on 1-abs(PE)
for n = 1:size(dat.u_bin,2)
    dat.ehgf_PE_abs.sub(n).est = tapas_fitModel(10.*dat.y_mc(:,n),...
        10.*(1.-abs(dat.u_pe(:,n))),...
        tapas_ehgf_config,...
        tapas_gaussian_obs_config,...
        tapas_quasinewton_optim_config ...
        );
    tapas_ehgf_plotTraj(dat.ehgf_PE_abs.sub(n).est)
    hold on;
    ax=axis;
    fill([dat.trials, fliplr(dat.trials)],...
        [ax(3)*ones(1,length(dat.trials)), ax(4)*ones(1,length(dat.trials))],...
        [dat.u_mab4', fliplr(dat.u_mab4')], 'EdgeAlpha', 0, 'FaceAlpha', 0.15);
    colormap(flipud(colormap("autumn")))
    hold off;
    figdir = fullfile('figures', 'mc_ehgf', ['est_absPE_sub' num2str(n)]);
    print(figdir, '-dpng');
end


%% fit metacognitive HGF + gaussian obs on PE+1 (scaling???)
for n = 1:size(dat.u_bin,2)
    dat.ehgf_PE.sub(n).est = tapas_fitModel(10.*dat.y_mc(:,n),...
        10.*(1+dat.u_pe(:,n)),...
        tapas_ehgf_config,...
        tapas_gaussian_obs_config,...
        tapas_quasinewton_optim_config ...
        );
    tapas_ehgf_plotTraj(dat.ehgf_PE.sub(n).est)
    hold on;
    ax=axis;
    fill([dat.trials, fliplr(dat.trials)],...
        [ax(3)*ones(1,length(dat.trials)), ax(4)*ones(1,length(dat.trials))],...
        [dat.u_mab4', fliplr(dat.u_mab4')], 'EdgeAlpha', 0, 'FaceAlpha', 0.15);
    colormap(flipud(colormap("autumn")))
    hold off;
    figdir = fullfile('figures', 'mc_ehgf', ['est_PE_sub' num2str(n)]);
    print(figdir, '-dpng');
end


end